# name of our workflow
name: Django CI/CD Workflow

# triggers for our workflow
on:
  # opening a pull request to master and develop branch will be a trigger
  pull_request:
    branches:
      - develop
      - master
      - tests/ci
  # any code pushed to master and develop branch will also be a trigger
  push:
    branches:
      - master
      - develop
      - tests/ci


# three job definition
jobs:
  test-job: # health check job for testing and code formatting check
    runs-on: ubuntu-latest # os for running the job
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2

      - name: Cache dependency # caching dependency will make our build faster.
        uses: actions/cache@v2 # for more info checkout pip section documentation at https://github.com/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup python environment # setting python environment to 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # if you want multiple python version run just use matrix strategy in job config. See the documentation of GitHub Actions

      - name: Check Python version # checking the python version to see if 3.x is installed.
        run: python --version

      - name: Criar arqui .env
        run: echo "EMAIL_HOST_PASSWORD=teste" > .env

      - name: Install requirements # install application requirements
        run: pip install -r requirements.txt

      - name: Run Migrations # run migrations to create table in side car db container
        run: python manage.py migrate

      - name: Run Test # running tests
        run: python manage.py test
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: davidmaxdmao/django-login:latest
